version: '2'

services:
  cuda:
    build: .
    container_name: cuda8.0
    volumes: 
    - ./project:/root/project
    - /tmp/.X11-unix:/tmp/.X11-unix # for X window GUI
    environment:
    - DISPLAY=$DISPLAY # for Xwindow GUI
  
  tensorflow:
    #build: ./Dockerfile_tensorflow
    image: gcr.io/tensorflow/tensorflow:latest-gpu
    container_name: tensorflow
    ports:
    - "8888"
    volumes: 
    - ./project:/root/project
    - /tmp/.X11-unix:/tmp/.X11-unix # for X window GUI
    environment:
    - DISPLAY=$DISPLAY # for Xwindow GUI

