version: '2'

services:
  cuda:
    build:
      context: .
      dockerfile: Dockerfile_cuda
    container_name: cuda8.0
    volumes: 
    - ./project:/root/project
    - /tmp/.X11-unix:/tmp/.X11-unix # for X window GUI
    environment:
    - DISPLAY=$DISPLAY # for Xwindow GUI
    restart: always
  tensorflow:
    build:
      context: .
      dockerfile: Dockerfile_tensorflow
    container_name: tensorflow
    ports:
    - "8888:8888"
    volumes: 
    - ./project/jupyter/notebooks:/notebooks
    - ./project:/root/project
    - /tmp/.X11-unix:/tmp/.X11-unix # for X window GUI
    environment:
    - DISPLAY=$DISPLAY # for Xwindow GUI
    restart: always
