services:
  cuda:
    build: .
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    environment:
    - DISPLAY=$DISPLAY
    volumes:
    - ./project:/root/project
    - /tmp/.X11-unix:/tmp/.X11-unix
    - nvidia_driver_384.69:/usr/local/nvidia:ro
version: '2'
volumes:
  nvidia_driver_384.69:
    external: true
