services:
  cuda80:
    build:
      context: .
      dockerfile: Dockerfile_cuda80
    cap_add:
    - SYS_ADMIN
    container_name: cuda80
    devices:
    - /dev/fuse:/dev/fuse
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    entrypoint: /usr/sbin/sshd -d
    environment:
    - DISPLAY=$DISPLAY
    ports:
    - '88:22'
    restart: always
    security_opt:
    - apparmor:unconfined
    stdin_open: true
    tty: true
    volumes:
    - ./project:/root/project
    - /tmp/.X11-unix:/tmp/.X11-unix
    - nvidia_driver_387.12:/usr/local/nvidia:ro
  cuda90:
    build:
      context: .
      dockerfile: Dockerfile_cuda90
    cap_add:
    - SYS_ADMIN
    container_name: cuda90
    devices:
    - /dev/fuse:/dev/fuse
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    entrypoint: /usr/sbin/sshd -d
    environment:
    - DISPLAY=$DISPLAY
    ports:
    - '89:22'
    restart: always
    security_opt:
    - apparmor:unconfined
    stdin_open: true
    tty: true
    volumes:
    - ./project:/root/project
    - /tmp/.X11-unix:/tmp/.X11-unix
    - nvidia_driver_387.12:/usr/local/nvidia:ro
  tensorflow:
    build:
      context: .
      dockerfile: Dockerfile_tensorflow
    container_name: tensorflow
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    environment:
    - DISPLAY=$DISPLAY
    - PASSWORD=12345678
    ports:
    - 8888:8888
    restart: always
    volumes:
    - ./project/jupyter/notebooks:/notebooks
    - ./project:/root/project
    - /tmp/.X11-unix:/tmp/.X11-unix
    - nvidia_driver_387.12:/usr/local/nvidia:ro
version: '2'
volumes:
  nvidia_driver_387.12:
    external: true
